### PR TITLE
Cli feature

### LINKED ISSUE #27: [Idea] Wrap all the commands in CLI
A simple CLI using something like [commander](https://www.npmjs.com/package/commander) or any other argv parser ([yargs](https://www.npmjs.com/package/yargs)?).
This could have the `build`, `blog`, `update` commands.

Then this could be published to npm too, and one would be able to run it as:
`npx gitfolio build --username xxx`

I could open a basic PR if this seems like a good idea.

### PR DESCRIPTION
**Pull request by rohit-gohri**
Closes #27 
### Entry

```sh
> npm run cli
Usage: gitfolio <command> [options]

Options:
  -v --version                output the version number
  -h, --help                  output usage information

Commands:
  build [options] <username>  Build site with your GitHub username. This will be used to customize your site
  update
  blog [options] <title>      Create blog with specified title
```

### Build
Made `username` an argument instead of an option as it is required always. This way commander handles the checks and logs. 
```sh
> npm run cli -- build --help
Usage: build [options] <username>

Build site with your GitHub username. This will be used to customize your site

Options:
  -t, --theme [theme]            specify a theme to use
  -b, --background [background]  set the background image
  -f, --fork                     includes forks with repos
  -s, --sort [sort]              set default sort for repository
  -o, --order [order]            set default order on sort
  -h, --help                     output usage information
```

### Blog
Similarly made `title` an argument too.
```sh
> npm run cli -- blog --help
Usage: blog [options] <title>

Create blog with specified title

Options:
  -s, --subtitle [subtitle]    give blog a subtitle (default: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.")
  -p, --pagetitle [pagetitle]  give blog page a title
  -f, --folder [folder]        give folder a title (use "-" instead of spaces)
  -h, --help                   output usage information
```

### Update
```sh
> npm run cli -- update --help
Usage: update [options]

Options:
  -h, --help  output usage information
```

# Changes:
- Moved default `config.json` and `blog.json` to default folder. 
- Changed all `./dist` references to `outDir`
- Added env variable OUT_DIR to overwrite outDir, by default it is set to cwd in CLI (Solves #39 kind of, could make it an option too?)
- Added npm run script `cli` to test while developing, sets OUT_DIR to `./dist`
- Added utilities to read `config.json` and `blog.json`, which fallback to default ones

### CODE REVIEW

**Comment by imfunniee** [comment]
no `build` also runs subsequent times, `update` is just to update the user and repo info. if someone needs to update their background or theme they need to run the `build` command again

**Comment by rohit-gohri** [comment]
> no `build` also runs subsequent times, `update` is just to update the user and repo info. if someone needs to update their background or theme they need to run the `build` command again

Cool. So I guess the current commands are settled.

**Comment by imfunniee** [comment]
oh shit wth, i thought "ready for review" meant you could check the progress lol mb

**Comment by rohit-gohri** [comment]
> oh shit wth, i thought "ready for review" meant you could check the progress lol mb

Haha. It's cool. I'll merge the changes in master today

**Comment by rohit-gohri** [comment]
@imfunniee Rebased from master. Please pull the base branch to show a proper diff or I can change PR base?.
Updated the PR description with all the changes.

Tested the cli on local, it works as expected

**Comment by imfunniee** [comment]
Change it `master_clone` 😄

**Comment by imfunniee** [comment]
will look into this in morning, good job 🙌

**Pull request merged**
