### PR TITLE
feat(repository): do not output archive git repository

### PR DESCRIPTION
**Pull request by FlorentinDUBOIS**
Hello!

This project is awesome, but I found weird to see archived repositories in the generated website. So, I create an option `--no-archive` to remove archive repositories before the render.

### CODE REVIEW

**Comment by imfunniee** [comment]
I'm sorry for having kept you waiting for so long, was working on making a base version of this from where people can contribute. Now that im are done with it could you please resolve the conflicting files by pulling in new changes and creating a PR again. 😄

**Review by overlineink — APPROVED** [review]

**Comment by overlineink** [comment]
I think you should leave this option enabled by default, why should I add archived repositories to my portfolio? There's no reason to be there, that's why we archived them. I guess `--add-archived` would be the right choise. 

Just consider my opinion, plz!

**Comment by imfunniee** [comment]
ye @overlineink is correct will make archive repos not show by default

**Comment by FlorentinDUBOIS** [comment]
I will do this soon ;)

**Comment by FlorentinDUBOIS** [comment]
Work in progress

**Pull request closed without merging**
