### PR TITLE
Added A Suite of Improvements

### PR DESCRIPTION
**Pull request by DonIsaac**
* Created site files are now placed in an output directory (defaults todist.)
* Output directory can be specified via the --out flat
* Added a ton of coments in build.js
* Made functions in build.js use bluebird promises
* Themes are now in the assets/templates folder instead as magic
strings in the source code
* Any number of custom themes (not just light and dark) can be used by creating
a [theme].css file and putting it in assets/themes
* CSS themes are rendered with Handlebars
* CSS themes now rely on Handlebars for specifying the background image
* Updated .gitignore

### CODE REVIEW

**Comment by imfunniee** [comment]
nice work @DonIsaac, gonna merge it if it all works out fine 😃👌

**Comment by imfunniee** [comment]
so umm it works perfectly fine with the build command but gives out an error whilst building a blog. 

```Error: Could not load link: "file:///D:/gitfolio/index.css"```

Basically its looking for index.css file in the working directory (gitfolio) which is now inside the `dist` folder. 

Moving the `index.html` file to dist folder also makes it not load blogs which again looks for `blog.json` inside the blog folder. 
Could you please move the blog section inside `dist` folder when its done building the index files (both html and css, you could have the blog folder inside assets until its done building) and look fix the paths inside blog.js? 

Then we can basically tell users to upload the content of `dist` file directly to their repo.

create a PR when you are done 👍😋

**Comment by DonIsaac** [comment]
@imfunniee thanks for letting me know, I’ll get that fixed and send a PR your way

**Comment by DonIsaac** [comment]
@imfunniee I made blog.js compatable with the output directory. However, the index.html page is not updated when a blog post is made. Not sure how that part works, or if blog.js is even responsible for that feature.

**Comment by imfunniee** [comment]
The `index.html` file looks for `blog.json` file which has the data it needs to show it on index which is inside `assets/blog`. 

No worries tho i'll look into that. Great work @DonIsaac 😄

**Comment by DonIsaac** [comment]
@imfunniee thanks brother, appreciate it :) if this request needs any more changes before merging let me know and I’ll make them.

**Comment by imfunniee** [comment]
ye it does, i working on them rn will PR your fork and then you can PR the master 👍😄

**Pull request merged**
