### PR TITLE
Added command to open the "index.html" from terminal.

### PR DESCRIPTION
**Pull request by sunn-e**

### CODE REVIEW

**Comment by sunn-e** [comment]
firxes issue #15

**Comment by imfunniee** [comment]
gonna use @oref one "navigate to index.html in your browser."

**Comment by benstigsen** [comment]
Or the index.html file could be dragged onto the browser

**Comment by hamogor** [comment]
Command line users (and unix users in general) wouldnt like that

**Comment by sunn-e** [comment]
> 
> 
> gonna use @oref one "navigate to index.html in your browser."

Why so much hassle, simply typing ```browser_name index.html``` would be fine. This is simpler than opening your browser seprately and navigating to the index.html. Please, reopen the PR @imfunniee

**Comment by hamogor** [comment]
Does this work in windows though?

**Pull request closed without merging**
